[project]
name = "mas-eval-week-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.1",
    "tiktoken>=0.5.0",
    "langfuse>=2.0.0",
    "requests>=2.31.0",
    "openai>=2.8.1",
    "dotenv>=0.9.9",
]
